name: publish

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: versions
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Setup Docker Buildx environment
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          build-args: |
            KAMAILIO_VERSION=${{ vars.KAMAILIO_VERSION }}
          push: true
          tags: mailsvb/kamailio:${{ vars.KAMAILIO_VERSION }},mailsvb/kamailio:latest
